version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-=(9g_65x**tzds^oyw+zf_(t!p112cop0k(b8c#tgxj%ok06sp
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - EMAIL_HOST_USER=grodnopythonclassdemo@gmail.com
      - EMAIL_HOST_PASSWORD=faqcY5-taqses-gofcib
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data: